-- JANSETU Supabase schema
-- PostgreSQL / Supabase-ready schema for JANSETU location hierarchy,
-- officer jurisdiction, complaints, and status timeline.

create extension if not exists "pgcrypto";

create table if not exists public.states (
  state_id bigint generated by default as identity primary key,
  state_name text not null unique,
  state_code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.districts (
  district_id bigint generated by default as identity primary key,
  district_name text not null,
  state_id bigint not null references public.states(state_id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (state_id, district_name)
);

create table if not exists public.areas (
  area_id bigint generated by default as identity primary key,
  area_name text not null,
  district_id bigint not null references public.districts(district_id) on delete cascade,
  pincode text not null,
  created_at timestamptz not null default now(),
  unique (district_id, area_name)
);

create table if not exists public.wards (
  ward_id bigint generated by default as identity primary key,
  ward_number text not null,
  ward_name text not null,
  area_id bigint not null references public.areas(area_id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (area_id, ward_number)
);

create table if not exists public.citizens (
  citizen_id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null unique,
  email text unique,
  password_hash text not null,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.officers (
  officer_id uuid primary key default gen_random_uuid(),
  badge_number text unique,
  name text not null,
  email text unique,
  password_hash text not null,
  phone text,
  role text not null default 'officer' check (role in ('officer', 'senior_officer', 'admin')),
  assigned_ward_id bigint references public.wards(ward_id) on delete set null,
  additional_ward_ids jsonb not null default '[]'::jsonb,
  district_id bigint references public.districts(district_id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.auth_users (
  auth_user_id uuid primary key default gen_random_uuid(),
  phone text unique,
  email text unique,
  password_hash text not null,
  role text not null check (role in ('citizen', 'officer', 'senior_officer', 'admin')),
  citizen_id uuid references public.citizens(citizen_id) on delete set null,
  officer_id uuid references public.officers(officer_id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.complaints (
  complaint_id uuid primary key default gen_random_uuid(),
  tracking_token text not null unique,
  citizen_id uuid references public.citizens(citizen_id) on delete set null,
  officer_id uuid references public.officers(officer_id) on delete set null,
  ward_id bigint references public.wards(ward_id) on delete set null,
  category text not null,
  text text not null,
  language text not null default 'en',
  lat numeric(10, 7),
  lng numeric(10, 7),
  address text,
  media_urls jsonb not null default '[]'::jsonb,
  ai_analysis jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'assigned', 'in_progress', 'resolved', 'rejected', 'escalated')),
  sla_days integer not null default 7,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.complaint_status_timeline (
  timeline_id uuid primary key default gen_random_uuid(),
  complaint_id uuid not null references public.complaints(complaint_id) on delete cascade,
  status text not null,
  note text,
  changed_by uuid references public.officers(officer_id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.jurisdiction_mappings (
  mapping_id uuid primary key default gen_random_uuid(),
  officer_id uuid not null references public.officers(officer_id) on delete cascade,
  ward_id bigint not null references public.wards(ward_id) on delete cascade,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (officer_id, ward_id)
);

create index if not exists idx_districts_state_id on public.districts(state_id);
create index if not exists idx_areas_district_id on public.areas(district_id);
create index if not exists idx_wards_area_id on public.wards(area_id);
create index if not exists idx_officers_assigned_ward_id on public.officers(assigned_ward_id);
create index if not exists idx_officers_district_id on public.officers(district_id);
create index if not exists idx_auth_users_phone on public.auth_users(phone);
create index if not exists idx_auth_users_email on public.auth_users(email);
create index if not exists idx_complaints_tracking_token on public.complaints(tracking_token);
create index if not exists idx_complaints_officer_id on public.complaints(officer_id);
create index if not exists idx_complaints_ward_id on public.complaints(ward_id);
create index if not exists idx_status_timeline_complaint_id on public.complaint_status_timeline(complaint_id);
create index if not exists idx_jurisdiction_officer_id on public.jurisdiction_mappings(officer_id);
create index if not exists idx_jurisdiction_ward_id on public.jurisdiction_mappings(ward_id);

alter table public.states enable row level security;
alter table public.districts enable row level security;
alter table public.areas enable row level security;
alter table public.wards enable row level security;
alter table public.citizens enable row level security;
alter table public.auth_users enable row level security;
alter table public.officers enable row level security;
alter table public.complaints enable row level security;
alter table public.complaint_status_timeline enable row level security;
alter table public.jurisdiction_mappings enable row level security;

create policy "Public read states" on public.states for select using (true);
create policy "Public read districts" on public.districts for select using (true);
create policy "Public read areas" on public.areas for select using (true);
create policy "Public read wards" on public.wards for select using (true);

create policy "Citizen can read own profile" on public.citizens for select using (auth.uid()::text = citizen_id::text);
create policy "Citizen can insert own profile" on public.citizens for insert with check (true);

create policy "Auth users self read" on public.auth_users for select using (auth.uid()::text = auth_user_id::text);
create policy "Auth users self update" on public.auth_users for update using (auth.uid()::text = auth_user_id::text);

create policy "Officer can read own record" on public.officers for select using (auth.uid()::text = officer_id::text);
create policy "Officer can update own record" on public.officers for update using (auth.uid()::text = officer_id::text);

create policy "Citizen can read complaints" on public.complaints for select using (true);
create policy "Citizen can create complaints" on public.complaints for insert with check (true);
create policy "Officer can update complaints" on public.complaints for update using (true);

create policy "Read complaint timeline" on public.complaint_status_timeline for select using (true);
create policy "Insert complaint timeline" on public.complaint_status_timeline for insert with check (true);

create policy "Read jurisdiction mappings" on public.jurisdiction_mappings for select using (true);
create policy "Insert jurisdiction mappings" on public.jurisdiction_mappings for insert with check (true);
create policy "Update jurisdiction mappings" on public.jurisdiction_mappings for update using (true);

insert into public.states (state_name, state_code) values
  ('Madhya Pradesh', 'MP'),
  ('Maharashtra', 'MH')
on conflict do nothing;

insert into public.districts (district_name, state_id)
select 'Bhopal', state_id from public.states where state_code = 'MP'
on conflict do nothing;

insert into public.areas (area_name, district_id, pincode)
select 'Kolar', district_id, '462042' from public.districts where district_name = 'Bhopal'
on conflict do nothing;

insert into public.wards (ward_number, ward_name, area_id)
select '12', 'Kolar Main Ward', area_id from public.areas where area_name = 'Kolar'
on conflict do nothing;

insert into public.citizens (citizen_id, name, phone, email, password_hash, address)
values
  ('11111111-1111-1111-1111-111111111111', 'Rahul Sharma', '9876543210', 'rahul.sharma@example.com', 'plain:password123', 'Bhopal, Madhya Pradesh')
on conflict do nothing;

insert into public.officers (officer_id, badge_number, name, email, password_hash, phone, role, assigned_ward_id, additional_ward_ids, district_id)
values
  ('22222222-2222-2222-2222-222222222222', 'BADGE-1001', 'Inspector Ramesh Kumar', 'ramesh.kumar@jansetu.gov.in', 'plain:officer123', '9000000001', 'officer', 1, '[2]'::jsonb, 1),
  ('33333333-3333-3333-3333-333333333333', 'BADGE-2001', 'Senior Officer Anika Sen', 'anika.sen@jansetu.gov.in', 'plain:officer123', '9000000002', 'senior_officer', null, '[]'::jsonb, 1)
on conflict do nothing;

insert into public.auth_users (auth_user_id, phone, email, password_hash, role, citizen_id, officer_id)
values
  ('44444444-4444-4444-4444-444444444444', '9876543210', 'rahul.sharma@example.com', 'plain:password123', 'citizen', '11111111-1111-1111-1111-111111111111', null),
  ('55555555-5555-5555-5555-555555555555', '9000000001', 'ramesh.kumar@jansetu.gov.in', 'plain:officer123', 'officer', null, '22222222-2222-2222-2222-222222222222'),
  ('66666666-6666-6666-6666-666666666666', '9000000002', 'anika.sen@jansetu.gov.in', 'plain:officer123', 'senior_officer', null, '33333333-3333-3333-3333-333333333333')
on conflict do nothing;

insert into public.complaints (
  complaint_id,
  tracking_token,
  citizen_id,
  officer_id,
  ward_id,
  category,
  text,
  language,
  lat,
  lng,
  address,
  media_urls,
  ai_analysis,
  status,
  sla_days
)
values (
  '77777777-7777-7777-7777-777777777777',
  'JST-DEMO-0001',
  '11111111-1111-1111-1111-111111111111',
  '22222222-2222-2222-2222-222222222222',
  1,
  'Roads',
  'Broken road near Kolar market',
  'en',
  19.0760000,
  72.8777000,
  'Kolar, Bhopal',
  '[]'::jsonb,
  '{"category":"Road Safety","priority":"high","confidence":0.92}'::jsonb,
  'in_progress',
  7
)
on conflict do nothing;

insert into public.complaint_status_timeline (timeline_id, complaint_id, status, note, changed_by)
values
  ('88888888-8888-8888-8888-888888888888', '77777777-7777-7777-7777-777777777777', 'pending', 'Complaint created', null),
  ('99999999-9999-9999-9999-999999999999', '77777777-7777-7777-7777-777777777777', 'in_progress', 'Assigned to officer', '22222222-2222-2222-2222-222222222222')
on conflict do nothing;
